### ISSUE TITLE
Missing os_flavor "rocky" causing breakage for hcloud-rust

### ISSUE THREAD

**Issue by MathiasPius** [MaximilianKoestler/hcloud-openapi#15]
It looks like with the release of Rocky Linux as a supported operating system, "rocky" is missing as an enum variant for the os_flavor types, even in the [official OpenAPI spec](https://docs.hetzner.cloud/spec.json).

https://github.com/MaximilianKoestler/hcloud-openapi/blob/6b7851bbd5d29004517943b80cd3ff0ed0b7301d/openapi/hcloud.json#L2884-L2892

I've reported the issue to Hetzner, but I figured I'd report it here too since it impacts downstream projects such as hcloud-rust by breaking image listing (serde decode errors due to unknown variant `rocky`).

**Comment by MaximilianKoestler** [comment]
Thank you for the report.
This issue should be fixed with [spec release v0.7.0](https://github.com/MaximilianKoestler/hcloud-openapi/releases/tag/v0.7.0), it would indeed have been nice if Hetzner mentioned this somewhere in the docs.

I will inform the downstream maintainer for hcloud-rust of this change.

**Comment by HenningHolmDE** [comment]
Thanks for letting us know, @MathiasPius.

I just released version 0.10.0 for [hcloud-rust](https://github.com/HenningHolmDE/hcloud-rust) that contains the fixed enumeration and should fix any deserialization issues with Rocky Linux servers.
